
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ADD ADD_TAGS DELETE DELETE_TAGS F FILENAME GET LIST Q STAR T WORDinput : instructioninstruction : add_inst\n                   | query_inst\n                   | add_tags_inst\n                   | delete_tags_instadd_inst : ADD F file_list T tag_listquery_inst : inst Q tag_query_or_staradd_tags_inst : ADD_TAGS Q tag_query_or_star T tag_listdelete_tags_inst : DELETE_TAGS Q tag_query_or_star T tag_listinst : DELETE\n            | LIST\n            | GETfile_list : FILENAME\n                 | FILENAME file_listtag_list : WORD\n                | WORD tag_listtag_query_or_star : STAR\n                         | tag_query\n    tag_query : WORD\n                 | WORD tag_query'
    
_lr_action_items = {'ADD':([0,],[7,]),'ADD_TAGS':([0,],[9,]),'DELETE_TAGS':([0,],[10,]),'DELETE':([0,],[11,]),'LIST':([0,],[12,]),'GET':([0,],[13,]),'$end':([1,2,3,4,5,6,20,21,22,23,28,31,32,33,34,35,],[0,-1,-2,-3,-4,-5,-7,-17,-18,-19,-20,-6,-15,-8,-9,-16,]),'F':([7,],[14,]),'Q':([8,9,10,11,12,13,],[15,16,17,-10,-11,-12,]),'FILENAME':([14,19,],[19,19,]),'STAR':([15,16,17,],[21,21,21,]),'WORD':([15,16,17,23,26,29,30,32,],[23,23,23,23,32,32,32,32,]),'T':([18,19,21,22,23,24,25,27,28,],[26,-13,-17,-18,-19,29,30,-14,-20,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'input':([0,],[1,]),'instruction':([0,],[2,]),'add_inst':([0,],[3,]),'query_inst':([0,],[4,]),'add_tags_inst':([0,],[5,]),'delete_tags_inst':([0,],[6,]),'inst':([0,],[8,]),'file_list':([14,19,],[18,27,]),'tag_query_or_star':([15,16,17,],[20,24,25,]),'tag_query':([15,16,17,23,],[22,22,22,28,]),'tag_list':([26,29,30,32,],[31,33,34,35,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> input","S'",1,None,None,None),
  ('input -> instruction','input',1,'p_input','ply_parser.py',86),
  ('instruction -> add_inst','instruction',1,'p_instruction','ply_parser.py',90),
  ('instruction -> query_inst','instruction',1,'p_instruction','ply_parser.py',91),
  ('instruction -> add_tags_inst','instruction',1,'p_instruction','ply_parser.py',92),
  ('instruction -> delete_tags_inst','instruction',1,'p_instruction','ply_parser.py',93),
  ('add_inst -> ADD F file_list T tag_list','add_inst',5,'p_add_inst','ply_parser.py',97),
  ('query_inst -> inst Q tag_query_or_star','query_inst',3,'p_query_inst','ply_parser.py',103),
  ('add_tags_inst -> ADD_TAGS Q tag_query_or_star T tag_list','add_tags_inst',5,'p_add_tags_inst','ply_parser.py',109),
  ('delete_tags_inst -> DELETE_TAGS Q tag_query_or_star T tag_list','delete_tags_inst',5,'p_delete_tags_inst','ply_parser.py',115),
  ('inst -> DELETE','inst',1,'p_inst','ply_parser.py',121),
  ('inst -> LIST','inst',1,'p_inst','ply_parser.py',122),
  ('inst -> GET','inst',1,'p_inst','ply_parser.py',123),
  ('file_list -> FILENAME','file_list',1,'p_file_list','ply_parser.py',132),
  ('file_list -> FILENAME file_list','file_list',2,'p_file_list','ply_parser.py',133),
  ('tag_list -> WORD','tag_list',1,'p_tag_list','ply_parser.py',140),
  ('tag_list -> WORD tag_list','tag_list',2,'p_tag_list','ply_parser.py',141),
  ('tag_query_or_star -> STAR','tag_query_or_star',1,'p_tag_query_or_star','ply_parser.py',148),
  ('tag_query_or_star -> tag_query','tag_query_or_star',1,'p_tag_query_or_star','ply_parser.py',149),
  ('tag_query -> WORD','tag_query',1,'p_tag_query','ply_parser.py',157),
  ('tag_query -> WORD tag_query','tag_query',2,'p_tag_query','ply_parser.py',158),
]
